apiVersion: v1
kind: Service
metadata:
  name: node-port-rabbitmq-management
  namespace: expert
spec:
  selector:
    app: deployment-rabbitmq
  ports:
    - protocol: TCP
      nodePort: 30012
      port: 15672
      targetPort: 15672
  type: NodePort
