apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-ui
  namespace: identity
spec:
  selector:
    matchLabels:
      app: deployment-identity-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-identity-ui
    spec:
      containers:
      - name: identity-ui
        image: 10.158.12.45:5001/identity/identity_ui:latest
        imagePullPolicy: Always
        env:
        - name: VUE_APP_COOKIE_DOMAIN_NAME
          value: "cn-idir.asia.pwcinternal.com"
        - name: VUE_APP_HOMEPAGE_ROOT_URL
          value: https://cn-idir.asia.pwcinternal.com:50000
        - name: VUE_APP_IDENTITY_HOST
          value: https://cn-idir.asia.pwcinternal.com:443/v1
        - name: VUE_APP_FOOTER_TEXT
          value: "©2019 苏州美能华智能科技有限公司"
        - name: VUE_APP_ACCOUNT_SAML
          value: saml
        resources: {}
      imagePullSecrets:
      - name: meinenghua
      nodeSelector: 
        node-tag: gpu-001
