apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-postgres
  namespace: identity
spec:
  selector:
    app: deployment-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP