apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: identity
spec:
  selector:
    matchLabels:
      app: deployment-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-postgres
    spec:
      containers:
      - name: postgres
        image: 10.157.112.207:5001/postgres:11.5-alpine
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: credential
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
        resources: {}
      imagePullSecrets:
      - name: meinenghua
      nodeSelector: 
        node-tag: gpu-001
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: identity-postgres
