---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: expert-postgres
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
  hostPath:
    type: DirectoryOrCreate
    path: MOUNT_DATA_PATH_PLACEHOLDER/expert/postgres
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expert-postgres
  namespace: expert
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: expert-postgres