apiVersion: apps/v1
kind: Deployment
metadata:
  name: information-extraction-mt
  namespace: expert
spec:
  selector:
    matchLabels:
      app: deployment-information-extraction-mt
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-information-extraction-mt
    spec:
      containers:
      - name: information-extraction-mt
        image: IMAGE_BASEURL_PLACEHOLDER/expert/information_extraction:IMAGE_VERSION_PLACEHOLDER
        imagePullPolicy: Always
        env:
        - name: MT_HTTPS
          value: "0"
        - name: MT_INSTANCE_ID
          value: mt.primary
        - name: MT_MQHOST
          value: cluster-ip-rabbitmq.expert.svc.cluster.local
        - name: MT_PRIMARY
          value: "1"
        - name: MT_TRAINABLE
          value: "INFORMATION_EXTRACTION_TRAINING_PERIOD_PLACEHOLDER"
        - name: MT_MACHINE_ID
          value: "INFORMATION_EXTRACTION_SOFT_KEY_PLACEHOLDER"
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
      imagePullSecrets:
      - name: meinenghua
      nodeSelector: 
        node-tag: INFORMATION_EXTRACTION_NODE_SELECTOR_PLACEHOLDER
