apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-dialog-report-pipeline
  namespace: dialog
spec:
  selector:
    app: deployment-dialog-report-pipeline
  ports:
    - protocol: TCP
      port: 7009
      targetPort: 7009
  type: ClusterIP
  