apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-agent-management-ms
  namespace: dialog
spec:
  selector:
    app: deployment-agent-management-ms
  ports:
    - protocol: TCP
      port: 9401
      targetPort: 9401
  type: ClusterIP
  