---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: identity-postgres
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
  hostPath:
    type: DirectoryOrCreate
    path: /data2/identity/postgres
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-postgres
  namespace: identity
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: identity-postgres
