apiVersion: v1
kind: Service
metadata:
  name: node-port-nlp-ehic-contextual-faq
  namespace: dialog
spec:
  selector:
    app: deployment-nlp-ehic-contextual-faq
  ports:
    - protocol: TCP
      nodePort: 32680
      port: 6680
      targetPort: 6680
  type: NodePort
