apiVersion: apps/v1
kind: Deployment
metadata:
  name: information-extraction-gpu1
  namespace: expert
spec:
  selector:
    matchLabels:
      app: deployment-information-extraction-gpu1
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-information-extraction-gpu1
    spec:
      containers:
      - name: information-extraction-gpu1
        image: 10.158.12.45:5001/expert/information_extraction:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command: 
            - env 
            - "PYTHONPATH=/app"
            - python3.7
            - /app/package/healthcheck/general.py
          initialDelaySeconds: 60    
          periodSeconds: 60           
          timeoutSeconds: 5        
          failureThreshold: 2
        env:
        - name: MT_ESHOST
          value: http://cluster-ip-log-elasticsearch.logging.svc.cluster.local:9200
        - name: MT_GPU
          value: "1"
        - name: MT_TRAINER
          value: "1"
        - name: MT_INSTANCE_ID
          value: mt.gpu1
        - name: MT_MQHOST
          value: cluster-ip-rabbitmq.expert.svc.cluster.local
        - name: MT_TRAINABLE
          value: ""
        - name: MT_MACHINE_ID
          value: ""
        resources: {}
          # limits:
          #   nvidia.com/gpu: "1"
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        volumeMounts:
        - mountPath: /app/package/data/workspace
          name: workspace
        - mountPath: /app/package/data/session
          name: session  
      imagePullSecrets:
      - name: meinenghua
      nodeSelector: 
        node-tag: gpu-001
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: information-extraction-workspace
      - name: session
        persistentVolumeClaim:
          claimName: information-extraction-session
