apiVersion: apps/v1
kind: Deployment
metadata:
  name: information-extraction-mt
  namespace: expert
spec:
  selector:
    matchLabels:
      app: deployment-information-extraction-mt
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-information-extraction-mt
    spec:
      containers:
        - name: information-extraction-mt
          image: 10.157.112.207:5001/expert/information_extraction:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: true
            capabilities: {}
            privileged: true
            procMount: Default
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          env:
            - name: MT_HTTPS
              value: "0"
            - name: MT_INSTANCE_ID
              value: mt.primary
            - name: MT_MQHOST
              value: cluster-ip-rabbitmq.expert.svc.cluster.local
            - name: MT_PRIMARY
              value: "1"
            - name: MT_TRAINABLE
              value: ""
            - name: MT_MACHINE_ID
              value: ""
          resources: {}
      imagePullSecrets:
        - name: meinenghua
      nodeSelector:
        node-tag: gpu-001
