---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dialog-logs
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    type: DirectoryOrCreate
    path: MOUNT_DATA_PATH_PLACEHOLDER/dialog/logs
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dialog-logs
  namespace: dialog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: dialog-logs
---