apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-ui
  namespace: identity
spec:
  selector:
    matchLabels:
      app: deployment-homepage-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-homepage-ui
    spec:
      containers:
      - name: homepage-ui
        image: 10.157.112.207:5001/identity/homepage_ui:latest
        imagePullPolicy: Always
        env:
        - name: VUE_APP_ACCOUNT_ROOT_URL
          value: https://smartdocumentanalyser.asia.pwcinternal.com:50001
        - name: VUE_APP_COOKIE_DOMAIN_NAME
          value: "smartdocumentanalyser.asia.pwcinternal.com"
        - name: VUE_APP_DIALOG_ROOT_URL
          value: ""
        - name: VUE_APP_HOMEPAGE_ROOT_URL
          value: https://smartdocumentanalyser.asia.pwcinternal.com:50000
        - name: VUE_APP_IDENTITY_HOST
          value: https://smartdocumentanalyser.asia.pwcinternal.com:60000/v1
        - name: VUE_APP_NENG_ROOT_URL
          value: https://smartdocumentanalyser.asia.pwcinternal.com:50002
        - name: VUE_APP_PWC_DEPARTMENT
          value: InnoCentre
        resources: {}
      imagePullSecrets:
      - name: meinenghua
      nodeSelector: 
        node-tag: gpu-001
