apiVersion: v1
kind: Service
metadata:
  name: node-port-postgres
  namespace: dialog
spec:
  selector:
    app: deployment-postgres
  ports:
    - protocol: TCP
      nodePort: 30002
      port: 5432
      targetPort: 5432
  type: NodePort