---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dialog-postgres
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
  hostPath:
    type: DirectoryOrCreate
    path: MOUNT_DATA_PATH_PLACEHOLDER/dialog/postgres
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dialog-postgres
  namespace: dialog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: dialog-postgres