---
apiVersion: v1
data:
  rabbitmq-user: admin
  rabbitmq-erlang-cookie: IMAZXXSDUZDQYLVUGFMC
  rabbitmq-host: cluster-ip-rabbitmq.expert.svc.cluster.local
  rabbitmq-port: "5672"
  redis-host:	cluster-ip-redis.expert.svc.cluster.local
  redis-port: "6379"
kind: ConfigMap
metadata:
  name: variables
  namespace: expert
---
apiVersion: v1
data:
  # use this command to get base64 string: echo -n 'GiM6G53ZsnSQ' | base64
  postgres-password: R2lNNkc1M1pzblNR  
  # use this command to get base64 string: echo -n '1ZwTUC2bGh6E' | base64
  rabbitmq-password: MVp3VFVDMmJHaDZF
  # use this command to get base64 string: echo -n 'jmCloGirhZmm' | base64
  redis-password: am1DbG9HaXJoWm1t
kind: Secret
metadata:
  name: credential
  namespace: expert
type: Opaque