apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-rabbitmq
  namespace: dialog
spec:
  selector:
    app: deployment-rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: amqp
    - protocol: TCP
      port: 4369
      targetPort: 4369
      name: epmd
    - protocol: TCP
      port: 25672
      targetPort: 25672
      name: rabbitmq-dist  
  type: ClusterIP