apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: identity
spec:
  selector:
    matchLabels:
      app: deployment-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-postgres
    spec:
      containers:
        - name: postgres
          image: IMAGE_BASEURL_PLACEHOLDER/postgres:11.5-alpine
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: pyq5qaog3O00QeESDx6x
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
          resources: {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: identity-postgres
      imagePullSecrets:
        - name: meinenghua
      nodeSelector:
        node-tag: IDENTITY_NODE_SELECTOR_PLACEHOLDER
